

export const multiple_items = [
    {
      index: 1,
      milestone_no: 'MS001',
      task: 'Task A',
      description: 'Complete initial setup',
      comment: 'No issues found',
      location: 'Location A',
      configuration: 'Config A',
      start_date: '2023-09-01',
      end_date: '2023-09-05',
      working_days: 5,
      man_power: 10,
      quantity: 100,
      image:"",
    },
    {
      index: 2,
      milestone_no: 'MS002',
      task: 'Task B',
      description: 'Install components',
      comment: 'Delayed by 2 days',
      location: 'Location B',
      configuration: 'Config B',
      start_date: '2023-09-06',
      end_date: '2023-09-10',
      working_days: 4,
      man_power: 8,
      quantity: 200,
      image:"",
    },
    {
      index: 3,
      milestone_no: 'MS003',
      task: 'Task C',
      description: 'Test system',
      comment: 'Testing in progress',
      location: 'Location C',
      configuration: 'Config C',
      start_date: '2023-09-11',
      end_date: '2023-09-15',
      working_days: 5,
      man_power: 12,
      quantity: 150,
      image:"",
    },
    {
      index: 4,
      milestone_no: 'MS004',
      task: 'Task D',
      description: 'Finalize setup',
      comment: 'Minor adjustments needed',
      location: 'Location D',
      configuration: 'Config D',
      start_date: '2023-09-16',
      end_date: '2023-09-20',
      working_days: 5,
      man_power: 15,
      quantity: 120,
      image:"",
    },
    {
      index: 5,
      milestone_no: 'MS005',
      task: 'Task E',
      description: 'Handover to client',
      comment: 'Ready for handover',
      location: 'Location E',
      configuration: 'Config E',
      start_date: '2023-09-21',
      end_date: '2023-09-25',
      working_days: 5,
      man_power: 10,
      quantity: 110,
      image:"",
    },
    {
      index: 6,
      milestone_no: 'MS006',
      task: 'Task E',
      description: 'Handover to client',
      comment: 'Ready for handover',
      location: 'Location E',
      configuration: 'Config E',
      start_date: '2023-09-21',
      end_date: '2023-09-25',
      working_days: 5,
      man_power: 10,
      quantity: 110,
      image:"",
    },
    {
      index: 7,
      milestone_no: 'MS007',
      task: 'Task E',
      description: 'Handover to client',
      comment: 'Ready for handover',
      location: 'Location E',
      configuration: 'Config E',
      start_date: '2023-09-21',
      end_date: '2023-09-25',
      working_days: 5,
      man_power: 10,
      quantity: 110,
      image:"",
    }
  ]
  